# **RMSProp**

## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

### RMSprop

In [2]:
def df_w(w):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    dW = np.array([0.2 * w[0], 4 * w[1]], dtype=np.float32)
    return dW

In [3]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    S = gamma * S + (1 - gamma) * dW ** 2
    W = W - lr * dW / np.sqrt(S + epsilon)
    return W, S

In [4]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    for epoch in range(epochs):
        dW = df_w(W)
        W, S = optimizer(W, dW, lr, S, 0.9)
        results.append(W)
    return results

In [5]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.0513215, -1.0513167], dtype=float32),
 array([-3.4351976, -0.5915234], dtype=float32),
 array([-2.958937  , -0.32943937], dtype=float32),
 array([-2.5654628 , -0.17756478], dtype=float32),
 array([-2.2292054 , -0.09163253], dtype=float32),
 array([-1.9362674 , -0.04494496], dtype=float32),
 array([-1.6781766 , -0.02081422], dtype=float32),
 array([-1.4493496 , -0.00903558], dtype=float32),
 array([-1.2458818, -0.0036459], dtype=float32),
 array([-1.0649028 , -0.00135351], dtype=float32),
 array([-9.0420204e-01, -4.5644370e-04], dtype=float32),
 array([-7.6199627e-01, -1.3756263e-04], dtype=float32),
 array([-6.3677830e-01, -3.6259997e-05], dtype=float32),
 array([-5.2721506e-01, -8.1133439e-06], dtype=float32),
 array([-4.3207833e-01, -1.4747270e-06], dtype=float32),
 array([-3.5019833e-01, -2.0278264e-07], dtype=float32),
 array([-2.8043449e-01, -1.8422952e-08], dtype=float32),
 array([-2.2165969e-01, -7.6773077e-10], dtype=float32),
 arra